"use client";

import ErrorPage from "@/components/ui/ErrorPage";

const GlobalError = ({ error, reset }: { error: Error; reset: () => void }) => (
  <html lang="en" className="scroll-smooth">
    <head>
      <title>DKMS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </head>
    <body>
      <ErrorPage error={error} reset={reset} />
    </body>
  </html>
);

export default GlobalError;
