import Footer from "../components/ui/Footer";
import Navbar from "../components/ui/Navbar";

import "./globals.css";
import Providers from "./providers";

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <head>
      <title>DKMS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </head>
    <body className="flex flex-col min-h-screen">
      <Providers>
        <header className="bg-base-300">
          <Navbar />
        </header>
        <main className="container mx-auto p-4 md:px-8 flex-grow">
          {children}
        </main>
        <Footer />
      </Providers>
    </body>
  </html>
);

export default RootLayout;
